name: Bug Report
description: Report an issue with the dongle, Home Assistant, or web monitoring
title: "[BUG] Brief description of the issue"
labels: [bug]
assignees: ''

body:
  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Select the component related to your issue
      options:
        - Dongle
        - Home Assistant
        - Web Monitoring
      required: true

  - type: input
    id: version
    attributes:
      label: Version Information
      description: Enter the version of the integration, dongle firmware, or mark N/A if related to Web Monitoring
      placeholder: "<Enter version here>"
      required: true

  - type: markdown
    attributes:
      value: "**Media Attachments**\nAttach any images or videos showing the issue (if applicable)."

  - type: input
    id: mqtt_output
    attributes:
      label: MQTT Output
      description: If your issue is related to the Dongle, Home Assistant, or Web Monitoring, please provide the output from the MQTT topic `dongleID/status`
      placeholder: "<Paste MQTT output here>"
      required: false

  - type: textarea
    id: detailed_description
    attributes:
      label: Detailed Description
      description: Provide a detailed description of the issue, including steps to reproduce and expected behavior.
      placeholder: "Describe the issue in detail"
      required: true
