name: Dongle Feature Request
description: Suggest a new feature or enhancement for the dongle.
title: "[Dongle Feature] Brief description of the feature"
labels: ["enhancement", "dongle"]

body:
  - type: input
    id: feature_name
    attributes:
      label: "Feature Name"
      description: "Give a brief name for the feature you’re requesting."
      placeholder: "Enter feature name here"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: UI Or Firmware Feature?
      options:
        - UI
        - Firmware
      validations:
        required: true


  - type: textarea
    id: feature_description
    attributes:
      label: "Feature Description"
      description: "Provide a detailed description of the feature and how it would improve the dongle’s functionality."
      placeholder: "Describe the feature in detail"
    validations:
      required: true

  - type: textarea
    id: usage_scenarios
    attributes:
      label: "Usage Scenarios"
      description: "Explain scenarios where this feature would be useful."
      placeholder: "List possible use cases"
    validations:
      required: true

  - type: input
    id: firmware_version
    attributes:
      label: "Current Firmware Version"
      description: "Provide the current firmware version, if applicable."
      placeholder: "Enter firmware version"
    validations:
      required: true


